# Generated by Django 4.0.10 on 2023-12-29 05:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0002_alter_class_flashcard_sets_remove_class_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='members',
            field=models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
