# Generated by Django 4.0.10 on 2023-12-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_flashcardset_owner'),
        ('classes', '0005_alter_class_flashcard_sets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='flashcard_sets',
        ),
        migrations.AddField(
            model_name='class',
            name='flashcard_sets',
            field=models.ManyToManyField(blank=True, related_name='classes', to='flashcards.flashcardset'),
        ),
    ]
