# Generated by Django 4.0.10 on 2023-12-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_remove_class_flashcard_sets_class_flashcard_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='invite_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
