# Generated by Django 4.0.10 on 2023-12-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_class_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='invite_code',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
