# Generated by Django 4.0.10 on 2023-12-30 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0008_alter_class_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='members',
            field=models.ManyToManyField(related_name='classes_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
