# Generated by Django 4.0.10 on 2023-12-31 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_alter_class_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='invite_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
