# Generated by Django 4.0.10 on 2023-12-05 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_onetimepassword_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
