# Generated by Django 4.0.10 on 2023-12-26 06:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardsetviewer',
            name='question_types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Multiple Choice', 'Multiple Choice'), ('Written', 'Written')], default='Multiple Choice', max_length=23),
        ),
    ]
